### ISSUE TITLE
Connectors issues

### ISSUE THREAD

**Issue by jpmcfarland** [chStaiger/iBridges-Gui#103]
While surveying logging updates, I came across a potential set of issues related to the connectors.  The `manager.IrodsConnector` and the `Icommands.IrodsConnectorIcommands` classes, though having parallel names and functionality are not completely parallel.  Indeed, the iCommands connector is actually contained within the "main" connector.  This is by design, but the latter expects an `irods_put` and `irods_get` method that is missing and some type hints need adjusting.  Also, the `tickets.Tickets` class attempts switching between iCommands/Python functionality.  This should actually be in the main connector where the determination of the existence of the iCommands can be determined.

I believe it may be that some functionality has been adjusted and not all references updated appropriately.  This needs to be looked at to see if there may be more issues and to get things fixed.

I'm happy to have a look unless somebody else prefers to do so.

**Comment by jpmcfarland** [comment]
In addition to these issues, I also discovered that regardless of the setting of `Up-/Download with iCommands (linux only)`, if a Linux system has the iCommands present, it will use them and _not_ the Python versions.  This is likely another oversight.

**Comment by jpmcfarland** [comment]
Upon a more detailed look, I removed the iCommands functionality as a concept and for testing.  The extra method did not appear necessary.  If it desired, it will have to be written into the iCommands connector regardless.

**Comment by wurDevTim** [comment]
> In addition to these issues, I also discovered that regardless of the setting of `Up-/Download with iCommands (linux only)`, if a Linux system has the iCommands present, it will use them and _not_ the Python versions. This is likely another oversight.
> 
> This was discovered by noticing there were no logging messages for transfers where there should have been. Logging for transfers with iCommands will need to be update as well.

If I recall correctly we intend to remove the icommands up/download completely as soon as Jos finishes the new sync code. 
The reason for this is that besides the bug in the Tickets in the python API there is nothing the icommands can do that the pythonAPI cannot.

**Comment by chStaiger** [comment]
> > In addition to these issues, I also discovered that regardless of the setting of `Up-/Download with iCommands (linux only)`, if a Linux system has the iCommands present, it will use them and _not_ the Python versions. This is likely another oversight.
> > This was discovered by noticing there were no logging messages for transfers where there should have been. Logging for transfers with iCommands will need to be update as well.
> 
> If I recall correctly we intend to remove the icommands up/download completely as soon as Jos finishes the new sync code. The reason for this is that besides the bug in the Tickets in the python API there is nothing the icommands can do that the pythonAPI cannot.

I think if we can show that the python implementation is not slower than the icommands in calculating diffs and up and downloads with that is something we can consider.

**Comment by jpmcfarland** [comment]
> If I recall correctly we intend to remove the icommands up/download completely as soon as Jos finishes the new sync code. The reason for this is that besides the bug in the Tickets in the python API there is nothing the icommands can do that the pythonAPI cannot.

Indeed.  Until then, this will keep things consistent and we can remove it as part of the conversion to Python-only.

**Comment by chStaiger** [comment]
Usage of icommands in GUI is fixed in https://github.com/chStaiger/iBridges-Gui/pull/98/commits/eb12d6da8dc4e15782e6d0225f693617437f0f78 
PR #98

**Comment by chStaiger** [comment]
PR #105 is merged. Close?

**Comment by chStaiger** [comment]
CLI is also adjusted see PR #114 (already merged, only very small changes)
