### ISSUE TITLE
clicking on a row, but missing the data object name, does not update the whole GUI

### ISSUE THREAD

**Issue by trel** [chStaiger/iBridges-Gui#11]
When selecting a 'different' row in the browser view, the information panel at the bottom clears the existing information, but does not repopulate with the new row's information (preview, metadata, resources, etc.) unless the data object name is clicked on directly.

Selecting elsewhere on a row makes it 'highlight', and clears the bottom, but does not populate the bottom panel.

**Comment by chStaiger** [comment]
Ah, yes I know what to do.

**Comment by chStaiger** [comment]
Preview, metadata etc are now filled when clicking anywhere in a row of the browser table. Fix in branch *pyqt6*
