### ISSUE TITLE
Add Docker image creation for testing

### ISSUE THREAD

**Issue by jpmcfarland** [chStaiger/iBridges-Gui#136]
Recycle existing Dockerfile(s) to create images with various versions of iRODS between 4.2.9 and 4.3.x for the purpose of testing.

**Comment by chStaiger** [comment]
A pipeline for integration tests for iBridges:
https://github.com/chStaiger/iBridges-Integration-tests

Currently only includes iRODS 4.3.0 and python3.8.

**Comment by chStaiger** [comment]
It is already in the ibridges python package ... We will only need mockup tests for the gui
