### ISSUE TITLE
how to handle missing parameters in the irods environment file

### ISSUE THREAD

**Issue by wurDevTim** [chStaiger/iBridges-Gui#255]
Heey,

Don't think this matters for my issue, but for completion. I am using the latest pip instaled ibridges-gui (v1.1.0) with python 3.11.9.

During my latest tests I encountered some surprising behavior when fields the environment json are missing.
I know there is an option to check the json, but to my surprise the logs do not advise me to use it when I try to sign in with an incomplete json. 

I tried a few combinations, I will describe what happened.

Environment file 1:
```
{
    "connection_timeout": 500000,
    "irods_authentication_scheme": "pam_password",
    "irods_client_server_negotiation": "request_server_negotiation",
    "irods_client_server_policy": "CS_NEG_REQUIRE",
    "irods_encryption_algorithm": "AES-256-CBC",
    "irods_encryption_key_size": 32,
    "irods_encryption_num_hash_rounds": 16,
    "irods_encryption_salt_size": 8,
    "irods_host": "xx",
    "irods_port": 1247,
    "irods_user_name": "yy",
    "irods_zone_name": "Zone",
}
```
The python-iRODS and iBridges work dine with these. When trying to login to the ibridges-GUI it blocks and tells me to check the logs, which contain a clear message of what to change:
![no default resource](https://github.com/user-attachments/assets/7f782c9d-cec2-41de-9618-7828b55fce6f)

Updating the json by adding: `"irods_default_resource": "zzz"` seems to do the trick, I can now login. 
Uploading, downloading files in the browser work without flawlessly:
![download_login](https://github.com/user-attachments/assets/9a760c6b-c002-4854-9d10-560289fbff35)

Now lets try to sync a folder, after selecting the folder and collection and pressing upload it becomes quiet...
No messages in the logs, I only get a text in the GUI:
![sync_message](https://github.com/user-attachments/assets/abb60b98-cdac-4eec-b9c1-2177cfddfd8d)

Interesting, as that file has not change.
Starting the debugger, the source of the message is `prep_session_for_copy`  in gui_utils.py:
![callstack](https://github.com/user-attachments/assets/5ecc5b47-31c6-4c5c-b337-929da6282fa5)
Which checks the `irods_home` among other parameters: `session.home == env.get("irods_home", -1)` in `is_session_from_config`.
This check fails as the `irods_home` is not in the environment file, but you would not guess that based on the message.

to help prevent these confusing situation and prevent unexpected behavior of the GUI  I recommend to check if the json contains all fields the GUI uses/checks on before signing the user in. 
And if the json misses fields advising the user to click configuration > check configuration to fix the issue....

**Comment by wurDevTim** [comment]
Heey,

Interesting, I am running a fresh pip install: version 1.1.0.
To double check I deleted the project from my machine, created a new environment and pip installed the ibride-gui, same issue.

(venv) xx\venv\Scripts>pip list
Package            Version
------------------ -------
colorama           0.4.6
defusedxml         0.7.1
ibridges           1.1.0
ibridgesgui        1.1.0
pip                24.0
prettytable        3.11.0
PyQt6              6.7.1
PyQt6-Qt6          6.7.2
PyQt6_sip          13.8.0
python-irodsclient 2.1.0
setproctitle       1.3.3
setuptools         65.5.0
six                1.16.0
tqdm               4.66.5
wcwidth            0.2.13

**Comment by chStaiger** [comment]
@wurDevTim  I made some adjustemts to the login function in the branch 256-sync-bug. Can you please test it?

**Comment by wurDevTim** [comment]
Yess, in this branch it works as I expected:
![no riods home](https://github.com/user-attachments/assets/1f7d9f43-5c68-410e-a19a-46372610a46c)
After adding the irods_home to the config iBridges logs in successfully.

The check if the path is valid is also an nice addition. 
One small thing is that the check in the configuration editor does not verify if the irods_home is valid.
Letting me believe the json was edited correctly, while I skipped the leading '/'... Then when I try to login I get the message that the irods_home could not be found. 
The error is clear and correct, but it would be even nicer if the config validation performed the same checks as the login function.

**Comment by chStaiger** [comment]
Great. I understand that it would be nice to check everything in the validation. But we have a little bit of a chicken and egg problem here. I cannot verify irods paths without having a valid iRODS session. So we first need to do the "syntactical" check: Did the user set an irods-home? Syubsequently, in the login we get the password and a valid iRODS session and we can check whether the home exists ...

**Comment by trel** [comment]
you **could** check that 'irods_home' starts with a leading slash, but yes, not much more than that.

**Comment by wurDevTim** [comment]
Makes sense, as long as all the checks are performed we did what we can. 
When branch 256-sync-bug gets merged I consider this issue is solved.

Thanks for the quick fix!

**Comment by chStaiger** [comment]
Merged.
