### ISSUE TITLE
Implement automatic file synchronisation

### ISSUE THREAD

**Issue by jtersteegwur** [chStaiger/iBridges-Gui#33]
Create a tab where the user can create/update/delete a file or folder to monitor.
When triggered, the file/folder is syncronised to a remote irods instance.

File access axioms:
1) Ignore files from a treatment belonging to the current date
2) Ignore files that are locked

Things to configure per file/folder to monitor:

1. A (local) source file/folder
2. A (remote) destination path
3. A cron notation?
4. Checkbox to delete synchronized files/folder
   - delete a file only if MD5 checksum has been validated
   - delete files in order from old to young
   - delete a file if older than a week

**Comment by chStaiger** [comment]
@jtersteegwur, thank you for describing the new feature. The configuration looks very generic and reusable for all kinds of use cases which is really great!
I would have a question about the file axioms. I am not sure what you mean with "treatment". 
And concerning the  locked files, what creates the lock? Is that something specific to your use case or is it referring to a generic lock on the filesystem?

**Comment by jtersteegwur** [comment]
Those are left-over requirements from the use-case we want to resolve with this (more generic) implementation. I will do more research into the requirements before creating the PR for this issue.

@wurDevTim Care to weigh in on this?

As I interpret the file axioms:
* Originally, the 'script' runs daily, this could/should be generalised to something like a cron-notation
* We suspect we do not want to disturb/interrupt any ongoing experiment's file i/o.
    * As such, we ignore files which belong to any experiment that started today?
        * This would result in a whole lot of undesired edge-case behavior regarding synchronisation moments around midnight
    * We do not want to try to synchronise files that are currently being written to
