### ISSUE TITLE
icommands no longer needed

### ISSUE THREAD

**Issue by trel** [chStaiger/iBridges-Gui#4]
The python-irodsclient will use parallel transfer (multiple threads per file) automatically since [0.9.0](https://github.com/irods/python-irodsclient/releases/tag/v0.9.0).

I believe the icommands checking and switching can be removed from this application.

**Comment by chStaiger** [comment]
I am not so sure about that. When one wants to synchronise larger collections between the local filesystem and the iRODS instance, irsync is still faster and the checks whether data needs to be updated on the destination is more efficient. We tried to implement that with the two diff functions in the irodsConnector.py. But it is really much slower.

**Comment by trel** [comment]
I can see that.   Maybe the python library needs to learn a little bit of sync itself...

**Comment by chStaiger** [comment]
See also:
https://github.com/irods/python-irodsclient/issues/391

**Comment by chStaiger** [comment]
We will switch to the python package ibridges, so no icommands anylonger
