### ISSUE TITLE
Adjust session handling to work better with the reworked connector and GUI classes

### ISSUE THREAD

**Issue by jpmcfarland** [chStaiger/iBridges-Gui#73]
- move `ic.session.foo()` calls to appropriate methods in the connector classes (or only manager class?)
- reevaluate where session functionality (data, properties, etc.) is best placed (session.py, manager.py, elsewhere?)
- ensure the current session validity is checked consistently

**Comment by jpmcfarland** [comment]
Writing of the password cache seems broken somehow, but nowhere obvious.

**Comment by jpmcfarland** [comment]
> Writing of the password cache seems broken somehow, but nowhere obvious.

While `_ = self._session.server_version` checks the connection, it also releases it in a way that removes the stored PAM password(s) in `pam_pw_negotiated`, giving nothing to cache locally.  I'm not sure of the exact mechanism, but adding or replacing with `pool.get_connection()` fixes it.

**Comment by maartenschermer** [comment]
It seems that when `session::_write_pam_password()` is called (from here: https://github.com/chStaiger/iBridges-Gui/blob/develop/irodsConnector/session.py#L251), `self._session.pam_pw_negotiated` return an empty list, and the password-cache file isn't written as a result (https://github.com/chStaiger/iBridges-Gui/blob/develop/irodsConnector/session.py#L335).
I'm not familiar with the inner workings of the iRods-library, but I assume that `self._session.pam_pw_negotiated` is called too early, at a point where the underlying variable hasn't been set yet. When I explicitly call `_write_pam_password` (again) on the destruction of the IrodsConnector-class (in `manager.py`), `self._session.pam_pw_negotiated` _does_ return a list, and the cache file _does_ get written.

**Comment by jpmcfarland** [comment]
> An additional issue: even if the password cache file is present, there is currently no way of telling the IrodsConnector() to use it, because the condition `... and password != ''` in this line: https://github.com/chStaiger/iBridges-Gui/blob/develop/irodsConnector/manager.py#L40 prohibits the program to reach the point where the cache file is read (https://github.com/chStaiger/iBridges-Gui/blob/develop/irodsConnector/session.py#L177).

I will have a look.

**Comment by chStaiger** [comment]
@jpmcfarland  Can this issue be closed?

**Comment by jpmcfarland** [comment]
Yes!
