### ISSUE TITLE
Redesign irods connector automatically switch to icommands under the hood? 

### ISSUE THREAD

**Issue by wurDevTim** [chStaiger/iBridges-Gui#74]
Currently there are three types available:

- Python irods client (default)
- Icommands
- Anonymous user
There is a large amount of functional overlap between the different classes. 
As a result there is a considerable amount of duplicate code. 

Right now the Icommands are only used for operations the python client cannot do, or not as efficiently (iRsync). 
In this case it makes sense to automatically switch to Icommands if they are available. 
It's a design choice, but if we decide to keep working in this way, I suggest to remove 'icommands' option  from the mainmenu.

**Comment by chStaiger** [comment]
Yes we will do that. As soon as the icommands are available on the system where the client runs and the user specified the `~/.irods/irods_environment.json` we will use the icommands for transferring data (like the CLI does).

**Comment by chStaiger** [comment]
Ok, this discussion can be closed as with PR #105 and #114 we decided that if the icommands are available the user still has the last vote whether they should be used.
