### ISSUE TITLE
Redesign anonymous user

### ISSUE THREAD

**Issue by wurDevTim** [chStaiger/iBridges-Gui#75]
The overlapping functionality from the Icommands and python iRODS client has already been moved to subclasses. 
The next question is what to do with the anonymous user. 

Anonymous users should only be allowed to use a subset of the functionalities: login, see and download data, (anything else?)
In the current version the functions are reimplemented for the anonymous user. 
They should be combined where possible to remove the duplicate code.

**Comment by chStaiger** [comment]
No icommands any longer and the anonymous user login is postponed until there is a valid use case
