### ISSUE TITLE
Code style cleanup

### ISSUE THREAD

**Issue by jpmcfarland** [chStaiger/iBridges-Gui#82]
_This issue has a broad scope and we will need to decide when it should be done and discuss how it should be done.  Sooner is better than later.  And needless to say, any new code should certainly follow a convention.  I have implicitly proposed PEP 8 as it is the de facto standard for general Python code formatting, and similarly NumPy docstrings._

Consistently apply the PEP 8 conventions across the board in all manually written Python code and filenames/directories following:

https://peps.python.org/pep-0008/

Certain external library naming conventions cannot be changed, namely PyQt, but those that can, the entities in the UI files that intersect with the code (e.g., target widget names), should adhere where possible.

I can propose names of top-level modules, classes, and similar so we can discuss them prior to implementation.

It may also be an idea to pick a convention for the directory structure that is more typical of open-source Python projects, but still allows the various distribution, testing, and other tools to function properly.  For instance, something like this may be ideal:

- iBridges (repository name)
  - doc/
  - ibridges/
    - connector/
    - gui/
    - test/
    - utils/
    - ibridges.py
  - install.py
  - LICENSE
  - README.md
  - requirements.txt

As for docstrings, **ALWAYS USE DOCSTRINGS**.  The NumPy convention for docstrings is quite clear and readable:

https://numpydoc.readthedocs.io/en/latest/format.html

Current tasks:

- update internal naming (class/method/function/variable)
- [x] iBridges.py
- [ ] iBridgesCli.py
- [ ] gui/*py
- [ ] gui/ui_files/*
- [ ] irodsConnector/*py
- [ ] utils/*py

Other tasks:

- update external (file/directory) naming?
- restructure modules?

**Comment by jpmcfarland** [comment]
Now that PR #80 is merged, I can start adding missing documentation and type hinting, and basic internal naming updates I have been working on.  There will inevitably be some minor code optimizations and bug fixes as I also update unit tests.

It will be good to _eventually_ discuss the more major changes such as file remaining and repository restructuring, particularly the arguments for and against such an effort.

**Comment by chStaiger** [comment]
The package will get a complete make over ... closed for now
