### ISSUE TITLE
Allow iRODS backend to function independent of GUI frontend

### ISSUE THREAD

**Issue by jpmcfarland** [chStaiger/iBridges-Gui#85]
At the moment, the GUI is required to successfully create an iRODS session with the backend as the user _must_ choose an iRODS environment file before connecting.  This and other circumstances can cause errors that are not currently handled correctly or at all.

Add checks to give the appropriate (error) messages when the session is likely to fail or when it has failed unexpectedly.  Also add convenience introspection methods to facilitate this and to clarify the state of the context, connector, and associated classes.

**Comment by chStaiger** [comment]
I think this issue has been solved @jpmcfarland ?

**Comment by jpmcfarland** [comment]
Yes, indeed.
