### ISSUE TITLE
irods_env_file not set in session.py

### ISSUE THREAD

**Issue by chStaiger** [chStaiger/iBridges-Gui#93]
The session.py only reads the last irods_env from the ibridges_conf, but when we want to set a new irods_env_file it gets ignored.

**Comment by chStaiger** [comment]
We can now assemble all configurations in context and successively add them to the irodsConnector. The session instantiation however must be done with all necessary parameters to establish a connection to iRODS. In `connect` it is checked whether the authentication is successful.

```
import utils
import irodsConnector

context = utils.context.Context()
context.irods_environment
context.irods_env_file = "/../irods_environment.json"
context.irods_environment

ic = irodsConnector.manager.IrodsConnector()
ic.ibridges_configuration = context.ibridges_configuration
ic.irods_env_file = context.irods_env_file
ic.irods_environment = context.irods_environment
ic.connect()

In [10]: ic.session.has_valid_irods_session()
Out[10]: True

In [12]: ic.resources
Out[12]:
{'bundleResc': {'parent': None,
  'status': None,
  'context': None,
  'free_space': 0},
 'irodsResc': {'parent': None,
  'status': None,
  'context': None,
  'free_space': 0},
...
```

**Comment by chStaiger** [comment]
Yes, the bug description is not very clear. Here is what I found when I wanted to integrate the CLI with the new backend:

1. We have to set an environment file from the CLI config (which still looks a bit different than the configs for the GUI, but this we can straighten out later) or command line argument
2. Use the `context` to also load the json file once the file path is set.

```
# Set the irods_env_path
import utils
irods_env = "/path/to/irods_environment.json"
context = utils.context.Context()
context.irods_env_file = irods_env
```

This leads to an exception since the property `irods_env_file` is set to `None` as a global parameter
```
Input In [2], in <cell line: 1>()
----> 1 context.irods_env_file = irods_env

File ~/git-repos/iBridges-Gui/utils/context.py:174, in Context.irods_env_file(self, filename)
    172 self._irods_env_file = path.LocalPath(filename).expanduser()
    173 logging.debug(f'setting: {self._irods_env_file=}')
--> 174 self._irods_environment.filepath = self._irods_env_file
    175 import irodsConnector
    176 if isinstance(self.irods_connector, irodsConnector.manager.IrodsConnector):

AttributeError: 'NoneType' object has no attribute 'filepath'
```

So to work around that I first ask for the property `context.irods_environment` which will instantiate that object with the `filepath`:

```
In [3]: context.irods_environment
Out[3]: JsonConfig("{}")

In [4]: context.irods_environment.filepath
Out[4]: LocalPath("/My/path/to/irods_environment.json")
```

This sets the *fiepath* to the *last_ienv* and an instantiate sempty JsonConfig.
I can now set a new file path but the JsonConfig does not get updated

```
In [5]: context.irods_env_file = "/my/new/irods_environment.json"

In [6]: context.irods_environment
Out[6]: JsonConfig("{}")
```
This then in turn leads to the the artefact that when you log in with a password an empty irods environment is passed and the irods session is not instantiated.

I solved that by doing a little trick, I introduced a flag `self.reload` which is set to true every time the irods_env_path is changed. So the next time someone asks for the property irods_environment the file will get loaded as a JsonConfig object.

**Comment by chStaiger** [comment]
So it is an effect of #94

**Comment by jpmcfarland** [comment]
> I solved that by doing a little trick, I introduced a flag `self.reload` which is set to true every time the irods_env_path is changed. So the next time someone asks for the property irods_environment the file will get loaded as a JsonConfig object.

Be aware that the JsonConfig objects maintain the same dictionary object when reset.  This is necessary for continuity of the Context variables between iRODS sessions.  Please check that functionality following a 'Close session' is consistent.

**Comment by jpmcfarland** [comment]
> Yes, the bug description is not very clear. Here is what I found when I wanted to integrate the CLI with the new backend:
> 
> 1. We have to set an environment file from the CLI config (which still looks a bit different than the configs for the GUI, but this we can straighten out later) or command line argument
> 2. Use the `context` to also load the json file once the file path is set.
> 
> ```
> # Set the irods_env_path
> import utils
> irods_env = "/path/to/irods_environment.json"
> context = utils.context.Context()
> context.irods_env_file = irods_env
> ```
> 
> This leads to an exception since the property `irods_env_file` is set to `None` as a global parameter
> 
> ```
> Input In [2], in <cell line: 1>()
> ----> 1 context.irods_env_file = irods_env
> 
> File ~/git-repos/iBridges-Gui/utils/context.py:174, in Context.irods_env_file(self, filename)
>     172 self._irods_env_file = path.LocalPath(filename).expanduser()
>     173 logging.debug(f'setting: {self._irods_env_file=}')
> --> 174 self._irods_environment.filepath = self._irods_env_file
>     175 import irodsConnector
>     176 if isinstance(self.irods_connector, irodsConnector.manager.IrodsConnector):
> 
> AttributeError: 'NoneType' object has no attribute 'filepath'
> ```
> 
> So to work around that I first ask for the property `context.irods_environment` which will instantiate that object with the `filepath`:
> 
> ```
> In [3]: context.irods_environment
> Out[3]: JsonConfig("{}")
> 
> In [4]: context.irods_environment.filepath
> Out[4]: LocalPath("/My/path/to/irods_environment.json")
> ```
> 
> This sets the _filepath_ to the value in _last_ienv_ and an instantiates an empty JsonConfig. I can now set a new file path but the JsonConfig does not get updated
> 
> ```
> In [5]: context.irods_env_file = "/my/new/irods_environment.json"
> 
> In [6]: context.irods_environment
> Out[6]: JsonConfig("{}")
> ```
> 
> This then in turn leads to the the artefact that when you log in with a password an empty irods environment is passed and the irods session is not instantiated.
> 
> I solved that by doing a little trick, I introduced a flag `self.reload` which is set to true every time the irods_env_path is changed. So the next time someone asks for the property irods_environment the file will get loaded as a JsonConfig object.

As I stated in:

https://github.com/chStaiger/iBridges-Gui/pull/98/files#r1195296130

The GUI sets the filepath in the correct manner.  A similar procedure should work here without needing to modify the JsonConfig code.

**Comment by chStaiger** [comment]
I tested the GUI. I have two irods_environment.json files and after a session close I can connect using the other file. To check I connected to two different servers. So no negative effect on the GUI. But I will try the reset option, too. Thanks!
