### ISSUE TITLE
can connect check is not using the irods poort

### ISSUE THREAD

**Issue by wurDevTim** [chStaiger/iBridges-Gui#95]
IRODS allows users to change the portnumber from 1247. iBridges support this functionality except for the `connection check`:
https://github.com/chStaiger/iBridges-Gui/blob/1d38b5506536684afd1033d9faebd0db61f81801/utils/utils.py#LL748C1-L768C25

We should update this function to use the 'irods_port' from the environment json.

**Comment by chStaiger** [comment]
I am not so sure about that. In about 10 years I have not seen that any sysadmin would configure their iRODS instance to use a different control port. It is a bit like with HTTP, you expect it to use port 80, or postgresql etc.

**Comment by wurDevTim** [comment]
During the last weeks I visited 3 universities last week and I don't know why but they all used different ports. It's configurable in the json and the rest of iBridges already supports it, so seems like a small fix we should implement.

**Comment by chStaiger** [comment]
Then we go ahead with that!!!
