### ISSUE TITLE
Fix bugs converting from print statements

### ISSUE THREAD

**Issue by jpmcfarland** [chStaiger/iBridges-Gui#96]
Some malformed logging statements were caused by blindly converting from the original print statements.  The main issue is from statements such as:

```python
print(a, b, c)
```

converted to:

```python
logging.info(a, b, c)
```

causing an error because arguments after the first (the message) are considered to be string formatting arguments to the first.

**Comment by chStaiger** [comment]
I merged PR #97. Can this issue be closed?

**Comment by jpmcfarland** [comment]
Of course!
